name: artifacts

on:
  push:
    branches: ['artifacts']

jobs:
  create_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: generate files
        run:  for i in {1..5}; do echo "testcontent${i}" > "testfile${i}"; done
      - name: Create some artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: |
            **/testfile*

  consume_artifacts:
    needs: create_artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: download named artifacts
        uses: actions/download-artifact@v3
        with:
          name: test-artifacts
      - run: ls -l

  cleanup-list:
    needs: consume_artifacts
    runs-on: ubuntu-latest
    outputs:
      artifact-data: ${{ steps.get-workflow-artifacts.outputs.data }}
    steps:
      - uses: octokit/request-action@v2.x
        id: get-workflow-artifacts
        with:
          route: GET /repos/{owner}/{repo}/actions/runs/{run_id}/artifacts
          owner: collinmcneese-test
          repo: workflow-sandbox
          run_id: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ steps.get-workflow-artifacts.outputs.data }}
      - run: echo ${{ fromJson(steps.get-workflow-artifacts.outputs.data).artifacts }}

  cleanup:
    runs-on: ubuntu-latest
    needs: cleanup-list
    strategy:
      matrix:
        artifact: ${{ fromJson(needs.cleanup-list.outputs.artifact-data).artifacts }}
    steps:
      - uses: octokit/request-action@v2.x
        name: cleanup artifact
        with:
          route: DELETE /repos/{owner}/{repo}/actions/artifacts/{artifact_id}
          owner: collinmcneese-test
          repo: workflow-sandbox
          artifact_id: ${{ matrix.artifact.id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
