name: artifacts

on:
  push:
    branches: ['artifacts']

jobs:
  create_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: generate files
        run:  for i in {1..5}; do echo "testcontent${i}" > "testfile${i}"; done
      - name: Create some artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-artifacts
          path: |
            **/testfile*

  consume_artifacts:
    needs: create_artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: download named artifacts
        uses: actions/download-artifact@v3
        with:
          name: test-artifacts
      - run: ls -l

  cleanup:
    runs-on: ubuntu-latest
    needs: consume_artifacts
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          version: 16
      - run: npm install @octokit/action
      - run: npx node artifact.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
