name: cleanup

on:
  workflow_run:
    workflows: [artifacts]
    types:
      - completed

jobs:
  cleanup-list:
    permissions:
      actions: read
    runs-on: ubuntu-latest
    outputs:
      artifact-data: ${{ steps.get-workflow-artifacts.outputs.data }}
    steps:
      - uses: octokit/request-action@v2.1.4
        id: get-workflow-artifacts
        with:
          route: GET /repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cleanup:
    runs-on: ubuntu-latest
    needs: cleanup-list
    strategy:
      matrix:
        artifact: ${{ fromJson(needs.cleanup-list.outputs.artifact-data).artifacts }}
    steps:
      - uses: octokit/request-action@v2.1.4
        name: cleanup artifact
        with:
          route: DELETE /repos/${{ github.repository }}/actions/artifacts/${{ matrix.artifact.id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
