name: github-script

on:
  workflow_dispatch:

jobs:
  script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      id: step1
      with:
        result-encoding: string
        script: |
          return 'this is a message'
    - name: output
      run: echo ${{ steps.step1.outputs.result }} >> $GITHUB_STEP_SUMMARY
      
